### ISSUE TITLE
Can't get accounts.google.com:sub ForAnyValue:StringEquals to work

### ISSUE THREAD

**Issue by c4urself** [code-dot-org/aws-google#2]
Following the example given I wasn't able to reduce the scope of who's able to access the AWS role without changing it to:

```     "Condition": {
        "StringEquals": {
          "accounts.google.com:sub": [
            "000000000000000000000",
            "111111111111111111111"
          ],
          "accounts.google.com:aud": "arstarste.apps.googleusercontent.com"
        }
      }
```

**Comment by wjordan** [comment]
Interesting- the example in the `README` is copy/pasted from the trust policy in my working environment, so I'm not sure why it wouldn't also work for you just the same.

In any case, it does seem that `ForAnyValue:StringEquals` isn't needed for the condition anyway, so your updated policy does make for a simpler example. Thanks for the suggestion!

**Comment by c4urself** [comment]
Thanks! Great project, worked out-of-the-box for me.
